spring.application.name=backend

# URL del database: localhost perché Docker ha mappato la porta sul PC
spring.datasource.url=jdbc:postgresql://localhost:5432/unicam_project_db
spring.datasource.username=admin
spring.datasource.password=admin
# Importante: specifica il driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate: crea automaticamente le tabelle partendo dalle classi Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect