spring.application.name=backend

# --- CONFIGURAZIONE URL ---
# Ho inserito l'host 'aws-1-eu-central-1...' e la porta 6543 che vedo nella tua immagine.
# Ho lasciato ?sslmode=require che è fondamentale.
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require

# --- USERNAME ---
# Ho inserito l'utente specifico per il pooler che vedo nella tua immagine.
spring.datasource.username=postgres.moiseaoqjgnmoccyoqye

# --- PASSWORD ---
# Qui devi cancellare le parentesi e scrivere la tua password reale.
spring.datasource.password=jIzJ*NQWLJ^7

spring.datasource.driver-class-name=org.postgresql.Driver

# --- TRUCCHI SUPABASE (Transaction Mode) ---
# Questi sono obbligatori perché l'immagine dice "Does not support PREPARE statements"
spring.datasource.hikari.data-source-properties.binaryTransfer=false
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# --- ABILITIAMO LE TABELLE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect